services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db-desafio-votacao
      MYSQL_ROOT_PASSWORD: Lui$$05012013
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - desafio-votacao-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    container_name: desafio-votacao
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db-desafio-votacao
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Lui$$05012013
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - desafio-votacao-network
    restart: unless-stopped

networks:
  desafio-votacao-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
